### ISSUE TITLE
Train_clf.py issue

### ISSUE THREAD

**Issue by Luckytek** [gdewael/maldi-nn#2]
When running the Train_clf.py script I am getting constantly the following attribute error: File "C:\Users\Pavel\anaconda3\Lib\site-packages\h5torch\dataset.py", line 132, in __getitem__    if self.f["central"].attrs["mode"] == "N-D":
       ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AttrArray' object has no attribute 'attrs'. 
RKIpeaks.h5 file has been generated by the process_RKI.py script successfully (see HDFView printscreen)
![image](https://github.com/user-attachments/assets/33a378c4-c44d-483a-bd2b-7aafc3f8bbba)
Please recommend what could be the problem.
Thanks.
Pavel

**Comment by gdewael** [comment]
Hi Pavel,

Thanks for testing out our code.
It's curious, because I can't reproduce the error upon re-running using a fresh conda environment.
What version of python and `h5torch` are you using?
Additionally, how exactly have you used the `train_clf` script?

Kind regards, Gaetan

**Comment by Luckytek** [comment]
Hi Gaetan,

 

Thank you for your prompt response and for looking into this.

 

I’m using the following versions:

 

*	Python: version 3.11.5
*	h5torch: version 0.2.14

 

Regarding the usage of the train_clf.py script, here is the approach I followed:

 

1.	Preprocessing: I first ran the process_RKI.py script with the command „python process_RKI.py F:\RKI_ROOT\ F:\DRIAMS_ROOT\RKIraw.h5 F:\DRIAMS_ROOT\RKIbin.h5 F:\DRIAMS_ROOT\RKIpeaks.h5“ to generate the HDF5 files (RKI_raw.h5, RKI_bin.h5, RKI_peaks.h5). The files appeared to be correctly structured, as verified using HDFView.
2.	Training: After generating these files, I executed the train_clf.py script with the command „python train_clf.py F:/DRIAMS_ROOT/RKIpeaks.h5 logs/ trf M --devices "cpu" --lr 0.0005

 

This is when the AttributeError related to AttrArray lacking the attrs attribute occurred.

 

Kind regards,



Pavel

**Comment by gdewael** [comment]
You are using our code correctly.
Could you provide me with your complete environment setup (e.g. the output of `pip list`), so I can reproduce?

**Comment by gdewael** [comment]
In addition, can you run this piece of code without error?

```python
import h5torch

f = h5torch.File("F:/DRIAMS_ROOT/RKIpeaks.h5").to_dict()
f["central"].attrs
```

**Comment by Luckytek** [comment]
Hi Gaetan,

 

I've attached the complete environment setup as requested, including the output of pip list. 

 

Please let me know if there's any further information you need or if there are additional steps I should take.

 

Thanks again for your support.

 

Kind regards,



Pavel

**Comment by Luckytek** [comment]
It seems the code ran without immediate errors (see bellow).

 

When I add the print(f["central"].attrs) to the code the output or attributes is visible.

 

PS C:\Users\Pavel\maldi-nn\maldi_nn>  c:; cd 'c:\Users\Pavel\maldi-nn\maldi_nn'; 

& 'c:\Users\Pavel\Anaconda3\python.exe' 'c:\Users\Pavel\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher' '59313' '--' 'C:\Users\Pavel\gaetan_code.py' 

{'dtypes': array(['int32', 'int64'], dtype=object), 'filled_to': 11055, 'mode': 'N-D', 'shape': array([11055])}

**Comment by gdewael** [comment]
Then I must admit I'm quite stumped, as it is clear that -- unlike the error claims -- `f["central"]` as `AttrArray` does have an `attrs` attribute.

Do you encounter the same issue running the classifier on binned data + MLP? I.e.:
`python train_clf.py F:/DRIAMS_ROOT/RKIbin.h5 logs/ mlp M --devices "cpu" --lr 0.0005`

**Comment by Luckytek** [comment]
When I run python train_clf.py F:/DRIAMS_ROOT/RKIbin.h5 logs/ mlp M --devices "cpu" --lr 0.0005 

 

I am getting KeyError: "Unable to open object (object 'mz' doesn't exist)" as follows:

 

PS C:\Users\Pavel\maldi-nn\maldi_nn\scripts> python train_clf.py F:/DRIAMS_ROOT/RKIbin.h5 logs/ mlp M --devices "cpu" --lr 0.0005 Group 0 mode: vlen Central dataset mode: N-D Unstructured group mode: N-D Intensity dataset mode: N-D Traceback (most recent call last): File "C:\Users\Pavel\maldi-nn\maldi_nn\scripts\train_clf.py", line 292, in <module> main() File "C:\Users\Pavel\maldi-nn\maldi_nn\scripts\train_clf.py", line 147, in main check_and_log_attributes(f) File "C:\Users\Pavel\maldi-nn\maldi_nn\scripts\train_clf.py", line 56, in check_and_log_attributes mz_mode = safe_get_attr(f["0/mz"], "mode", "vlen") ~^^^^^^^^ File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper File "C:\Users\Pavel\anaconda3\Lib\site-packages\h5py\_hl\group.py", line 357, in __getitem__ oid = h5o.open(self.id, self._e(name), lapl=self._lapl) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper File "h5py\h5o.pyx", line 190, in h5py.h5o.open KeyError: "Unable to open object (object 'mz' doesn't exist)"

 

When I modify the process_RKI.py script so that the mz dataset is placed under the 0 group in the RKIbin.h5 file as follows:

 

def RKI_raw_to_binned(rawfile, processed_file):

    binner = SequentialPreprocessor(

        VarStabilizer(method="sqrt"),

        Smoother(halfwindow=10),

        BaselineCorrecter(method="SNIP", snip_n_iter=20),

        Trimmer(),

        Binner(),

        Normalizer(sum=1),

    )

    shutil.copy(rawfile, processed_file)

    f = h5torch.File(processed_file, "a")

    

    if '0/mz' not in f or '0/intensity' not in f:

        print("Datasets '0/mz' or '0/intensity' not found in the file. Aborting.")

        print(f"Available datasets in the file: {list(f.keys())}")

        f.close()

        return

 

    len_ = f["0/mz"].shape[0]

    ints = []

    mzs = None  # Initialize mzs variable

    for i in range(len_):

        mz = f["0/mz"][i]

        intensity = f["0/intensity"][i]

        s = SpectrumObject(mz=mz, intensity=intensity)

        processed_s = binner(s)

        ints.append(processed_s.intensity)

        if mzs is None:

            mzs = processed_s.mz  # Save the mz values once

 

        if (i + 1) % 1000 == 0:

            print(i, end=" ", flush=True)

 

    # Delete the old datasets

    del f["0/mz"]

    del f["0/intensity"]

 

    # Register the new intensity dataset under group "0"

    f.register(np.stack(ints), 0, name="intensity", dtype_save="float32")

    f["0/intensity"].attrs["mode"] = "N-D"

 

    # Register the mz dataset under group "0"

    f.register(mzs, 0, name="mz", dtype_save="float32")

    f["0/mz"].attrs["mode"] = "N-D"

 

    f.close()

    return None """

 

I am getting the ValueError: the number of rows in the given data does not equal the number of elements in the  central data object along its alignment axis like this J

 

PS C:\Users\Pavel\maldi-nn\maldi_nn\scripts> python process_RKI.py F:\RKI_ROOT\ F:\DRIAMS_ROOT\RKIraw.h5 F:\DRIAMS_ROOT\RKIbin.h5 F:\DRIAMS_ROOT\RKIpeaks.h5

Species: 11055, Locations: 11055, Splits: 11055

999 1999 2999 3999 4999 5999 6999 7999 8999 9999 10999 Traceback (most recent call last):

  File "C:\Users\Pavel\maldi-nn\maldi_nn\scripts\process_RKI.py", line 237, in <module>

    main()

  File "C:\Users\Pavel\maldi-nn\maldi_nn\scripts\process_RKI.py", line 233, in main

    RKI_raw_to_binned(spectraraw, spectrabin)

  File "C:\Users\Pavel\maldi-nn\maldi_nn\scripts\process_RKI.py", line 171, in RKI_raw_to_binned    f.register(mzs, 0, name="mz", dtype_save="float32")

    raise ValueError(

ValueError: the number of rows in the given data does not equal the number of elements in the   

central data object along its alignment axis.

**Comment by gdewael** [comment]
I can not reproduce any of your errors.
Normally, `process_RKI` should not be changed in order to make the scripts work, as I've tested out everything in a fresh conda environment.

Could you be so kind to try and install `maldi-nn` in a fresh new environment and try again?

Also, normally, you should be able to run `process_RKI` and `train_clf` as is (i.e. without preceding it by `python` and without including the `.py`. The pip install includes these scripts as executables in your PATH. This will make sure you're executing the right code.

Thanks.

**Comment by Luckytek** [comment]
Thank you for your guidance. I will follow your suggestion and set up a fresh conda environment to reinstall maldi-nn and run the scripts again.

 

I’ll let you know how it goes.

**Comment by Luckytek** [comment]
Hello Gaetan,

I wanted to update you on the progress I’ve made with the train_clf.

Fresh Installations

I have performed a fresh installation of Anaconda and set up the maldi-nn environment from scratch as you suggested (see the attached base_environment_packages list and maldi_nn_environment_packages list).

Current Issue

Despite these fresh installations, I am still encountering the same issue when trying to access attributes in the central dataset within an HDF5 file. Specifically:

*	When running the following script:

import h5torch

f = h5torch.File("F:/DRIAMS_ROOT/RKIpeaks.h5").to_dict()

print(f["central"].attrs)

I get the expected output with the attributes listed correctly:

{'dtypes': array(['int32', 'int32'], dtype=object), 'filled_to': np.int32(11055), 'mode': 'N-D', 'shape': array([11055], dtype=int32)}

 

However, when I run train_clf I get AttributeError: 'AttrArray' object has no attribute 'attrs' as follows: 

 

Exception has occurred: AttributeError

Caught AttributeError in DataLoader worker process 0. Original Traceback (most recent call last): File "c:\Users\Pavel\anaconda3\envs\maldi-nn\Lib\site-packages\torch\utils\data\_utils\worker.py", line 309, in _worker_loop data = fetcher.fetch(index) # type: ignore[possibly-undefined] ^^^^^^^^^^^^^^^^^^^^ File "c:\Users\Pavel\anaconda3\envs\maldi-nn\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] ~~~~~~~~~~~~^^^^^ File "c:\Users\Pavel\anaconda3\envs\maldi-nn\Lib\site-packages\h5torch\dataset.py", line 133, in __getitem__ if self.f["central"].attrs["mode"] == "N-D": ^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'AttrArray' object has no attribute 'attrs' 

File "C:\Users\Pavel\train_clf.py", line 267, in main trainer.fit(model, dm.train_dataloader(), dm.val_dataloader()) File "C:\Users\Pavel\train_clf.py", line 292, in <module> main() AttributeError: Caught AttributeError in DataLoader worker process 0. Original Traceback (most recent call last): File "c:\Users\Pavel\anaconda3\envs\maldi-nn\Lib\site-packages\torch\utils\data\_utils\worker.py", line 309, in _worker_loop data = fetcher.fetch(index) # type: ignore[possibly-undefined] ^^^^^^^^^^^^^^^^^^^^ File "c:\Users\Pavel\anaconda3\envs\maldi-nn\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] ~~~~~~~~~~~~^^^^^ File "c:\Users\Pavel\anaconda3\envs\maldi-nn\Lib\site-packages\h5torch\dataset.py", line 133, in __getitem__ if self.f["central"].attrs["mode"] == "N-D": ^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'AttrArray' object has no attribute 'attrs' 

*	 When I integrate similar code to to access attributes into the dataset.py file within h5torch, the script fails to print these attributes, and instead, I receive an output indicating that the attributes do not exist or are inaccessible:

print(f"self.f['central']: {self.f['central']}")

print(f"type(self.f['central']): {type(self.f['central'])}")

print(self.f["central"].attrs)

The output only shows:

self.f['central']: [  0   0   0 ... 269 269 269]

type(self.f['central']): <class 'h5torch.file.AttrArray'>

Attributes do not exist or are not accessible.

Given that the attributes are correctly accessible when using a simple script but not when accessed through the dataset.py module, I’m unsure where the disconnect might be happening.

Could you please provide further guidance on how to resolve this issue? Given the fresh installation, I’m hoping there might be a specific aspect of the h5torch package or the dataset interaction that I’m missing.

Thank you in advance for your help.

Pavel

 

 

From: ***@***.*** ***@***.*** 
Sent: Tuesday, August 20, 2024 1:47 PM
To: 'gdewael/maldi-nn'; 'gdewael/maldi-nn'
Cc: 'Author'
Subject: RE: [gdewael/maldi-nn] Train_clf.py issue (Issue #2)

 

Thank you for your guidance. I will follow your suggestion and set up a fresh conda environment to reinstall maldi-nn and run the scripts again.

 

I’ll let you know how it goes.

**Comment by gdewael** [comment]
Hi Pavel,

You set up the tests correctly: one script says that "in-memory loaded h5torch objects" (represented by a nested dict of AttrArrays) have the `.attrs` attribute, while the other does not. I have no clue what's going wrong as I also cannot reproduce your issues.

As a possible work-around, I have pushed a new release of `maldi-nn` (0.2.5) which allows you to set `--data_in_memory False` for the `train_clf` script. Can you check if updating `pip install -U maldi-nn` and running `train_clf` with this flag as False resolves your issue?

**Comment by Luckytek** [comment]
Hi Gaetan,Thank you very much, I will try your solution and I am back to you.Kind Regards,Pavel Sent from Android deviceDne 29. 8. 2024 15:35 napsal uživatel Gaetan De Waele ***@***.***>:
Hi Pavel,
You set up the tests correctly: one script says that "in-memory loaded h5torch objects" (represented by a nested dict of AttrArrays) have the .attrs attribute, while the other does not. I have no clue what's going wrong as I also cannot reproduce your issues.
As a possible work-around, I have pushed a new release of maldi-nn (0.2.5) which allows you to set --data_in_memory False for the train_clf script. Can you check if updating pip install -U maldi-nn and running train_clf with this flag as False resolves your issue?

**Comment by gdewael** [comment]
Closing after one year of inactivity.
